### ISSUE TITLE
STR_* possibly overriding default constants

### ISSUE THREAD

**Issue by aminnairi** [khalyomede/helpers-php#3]
### Issue
PHP's defaults constants might contain `STR_*` and is more likely to be than a `STR_RANDOM_*` constant.
### Enhancement
Re-engineer the [`str_random()`](https://github.com/khalyomede/helpers-php#str_random) function to use the following convention for constants
```
STR_RANDOM_ALNUM
STR_RANDOM_NUM
STR_RANDOM_ALPHA
...
```

**Comment by khalyomede** [comment]
**STR_** custom constants where meant to be general as they could be use by another `str_*` function later. Checking the default STR_* constants using `print_r(get_defined_constants(true));` in my web browser showed me that only `STR_PAD_LEFT`, `STR_PAD_RIGHT`, and `STR_PAD_BOTH` are set.

Should we rename into specific constants or keep it general (in case of further methods that could use those new constants) ? Knowing that I used `if( defined() )` to be safe.

**Comment by aminnairi** [comment]
I guess the argument for keeping them available for further methods is enough for us to keep the current constant convention. If you did checked with a defined() we are safe. For now 😄
